using HitCustomAnnotations.Interfaces;
using System;
using System.Collections.Generic;
using System.Text;

namespace HitCustomAnnotations.Classes
{
    [AttributeUsage(AttributeTargets.Class |
                    AttributeTargets.Struct,
                       AllowMultiple = true)  // Multiuse attribute.  
    ]


    public class SchedulerAnnotation : Attribute//, ISchedulerAnnotation
    {
        /// <summary>
        /// Unique guid id generated by author same for all releases
        /// </summary>
        public string serviceId { get; set; }

        /// <summary>
        /// Service decription
        /// </summary>
        public string description { get; set; }

        /// <summary>
        /// service version
        /// </summary>
        public string version { get; set; }

        /// <summary>
        /// the name of the service
        /// </summary>
        public string serviceName { get; set; }

        public SchedulerAnnotation(string _serviceId, string _serviceName, string _description, string _version)
        {
            serviceId = _serviceId;
            description = _description;
            version = _version;
            serviceName = _serviceName;
        }

        public string GetId()
        {
            return serviceId;
        }

        public string GetDescription()
        {
            return description;
        }

        public string GetVersion()
        {
            return version;
        }

        public string GetServiceName()
        {
            return serviceName;
        }
    }
}
